# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-21 22:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cantidad', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('nombre', models.CharField(max_length=25, null=True)),
                ('apellido', models.CharField(max_length=25, null=True)),
                ('cedula', models.IntegerField(primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=25, null=True)),
                ('fecha_nacimiento', models.DateField(max_length=255, null=True)),
                ('descripcion', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('custom_id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('precio', models.FloatField()),
                ('imagen', models.ImageField(upload_to='Facetool/media/')),
            ],
        ),
        migrations.AddField(
            model_name='carrito',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minitw.Producto'),
        ),
    ]
